// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Root = 2,
  Namespace = 3,
  Keyword = 130,
  NamespaceName = 5,
  Class = 6,
  ClassName = 8,
  ExtendsName = 10,
  Block = 11,
  Group = 12,
  String = 131,
  Number = 132,
  Char = 133,
  Punctuation = 134
